# Generated by Django 4.2 on 2024-07-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars'), (6, '6 Stars'), (7, '7 Stars'), (8, '8 Stars'), (9, '9 Stars'), (10, '10 Stars')]),
        ),
    ]
